name: vendor_tracker_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  isar_flutter_libs:
    path: local_packages/isar_flutter_libs
  isar: ^3.1.0+1
  path_provider: ^2.1.3
  provider: ^6.1.1
  intl: ^0.20.2 
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0

  
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/linen_dress.jpg
  #   - assets/images/silk_blouse.jpg
  #   - assets/images/lilac_sweater.jpg
  #   - assets/images/leather_jacket.jpg
  #   - assets/images/cotton_tshirt.jpg
  #   - assets/images/jeans.jpg


  
  
  
  